nexxtway/rainbow-modules

- packages/app/package.json
- packages/auth/package.json
- packages/firebase-hooks/package.json
- packages/icons/package.json
- @rainbow-modules/app@0.0.9
- @rainbow-modules/auth@0.0.9
- @rainbow-modules/firebase-hooks@0.0.4
- @rainbow-modules/icons@0.0.6
> chore: publish

- .storybook/main.js
- .storybook/preview.js
- package.json
- yarn.lock
> chore: add WebView addons to the library

- packages/icons/docs/stories/helpers/iconsArray.js
- packages/icons/docs/stories/rainbowIconsGallery.js
- packages/icons/src/components/check/index.js
- packages/icons/src/index.js
> feat: add Checkmark icon

- packages/icons/docs/stories/rainbowIconItem.js
> fix: docs of import text on icons modules

- .storybook/main.js
#120 
- fix: add @rainbow-modules/validation to .storybook/main.js
> fix: validation module

- packages/payment/docs/stories/CreditCardPicker.story.js
- packages/payment/src/components/CreditCardPicker/index.js
> fix: add labelAlignment on CreditCardPicker component

- packages/app/src/components/AppNotificationManager/styled.js
> fix: notification padding

- packages/payment/docs/components/CreditCardPicker.story.mdx
- packages/payment/docs/components/StripeCheckoutModal.story.mdx
> docs: fixed docs on creditcardpicker and stripecheckoutmodal

- packages/app/docs/stories/appNotification.story.js
> Docs appnotification module

- packages/app/docs/components/ConfirmModal.story.mdx
- packages/app/docs/stories/appConfirmModal.story.js
- packages/app/src/components/ConfirmModal/index.js
> Docs confirmmodal module

- packages/hooks/docs/hooks/useScrollingIntent.story.mdx
- packages/hooks/docs/stories/index.js
- packages/hooks/docs/stories/wrapperScrollingIntent.js
- packages/hooks/src/index.js
- packages/hooks/src/useScrollingIntent.js
> feat: add useScrollingIntent hook

- .storybook/main.js
- packages/record/docs/components/RecordField.story.mdx
- packages/record/docs/stories/RecordField.story.js
- packages/record/package.json
- packages/record/src/components/RecordField/index.js
- packages/record/src/components/RecordField/styled/index.js
- packages/record/src/index.js
> feat: created recordfield in rocord module

- packages/auth/docs/stories/emailPasswordSignInForm.story.js
> docs: fixed structure docs auth module

- packages/firebase-hooks/src/firestore/useBatch/__test__/batchDelete.spec.js
- packages/firebase-hooks/src/firestore/useBatch/__test__/batchSet.spec.js
> test: for `batchDelete` and `batchSet` hook

- packages/forms/src/components/UniversalForm/__test__/universalForm.spec.js
- packages/forms/src/helpers/__test__/composeValidators.spec.js
- packages/forms/src/helpers/__test__/withCustomError.spec.js
- packages/forms/src/validators/__test__/isEmail.spec.js
- packages/forms/src/validators/__test__/isRequired.spec.js
> test: for `UniversalForm` component

- packages/forms/package.json
- packages/hooks/docs/hooks/useConnectModal.story.mdx
- packages/hooks/package.json
- packages/hooks/src/modal/useConnectModal.js
> docs: add for useConnectModal & useOpenModal

- packages/firebase-hooks/docs/hooks/useAuthState.story.mdx
- packages/firebase-hooks/docs/hooks/useCollectionOnce.story.mdx
- packages/firebase-hooks/docs/hooks/useDoc.story.mdx
- packages/firebase-hooks/docs/hooks/useDocOnce.story.mdx
- packages/firebase-hooks/docs/hooks/useFirebaseApp.story.mdx
- packages/firebase-hooks/docs/stories/index.story.js
- packages/firebase-hooks/docs/stories/useAuthState.story.js
- packages/firebase-hooks/docs/stories/useCollection.story.js
- packages/firebase-hooks/docs/stories/useCollectionOnce.story.js
- packages/firebase-hooks/docs/stories/useDoc.story.js
- packages/firebase-hooks/docs/stories/useDocOnce.story.js
- packages/firebase-hooks/docs/stories/useFirebaseApp.story.js
> docs: document firebase-hooks

- packages/hooks/src/useMutationFlow/index.d.ts
> fix: add parameters types to mutate on useMutationFlow

- babel.config.js
- package.json
- packages/app/package.json
- packages/auth/package.json
- packages/content/package.json
- packages/dashboard/package.json
- packages/datetime/package.json
- packages/demos/package.json
- packages/firebase-hooks/package.json
- packages/forms/package.json
- packages/hooks/package.json
- packages/icons/package.json
- packages/layout/package.json
- packages/listview/package.json
- packages/mapbox/package.json
- packages/micro/package.json
- packages/misc/package.json
- packages/notifications/package.json
- packages/payment/package.json
- packages/record/package.json
- packages/search/package.json
- packages/storage/package.json
- packages/validation/package.json
- tsconfig.build.json
Reverts nexxtway/rainbow-modules#579
> chore: revert "chore: improve modules build"

- packages/app/src/actions/index.d.ts
> fix: variant type in showAppMessage

- packages/dashboard/docs/stories/Tile.story.js
- packages/dashboard/src/components/Tile/index.d.ts
- packages/dashboard/src/components/Tile/index.js
- packages/dashboard/src/components/Tile/styled.js
> feat: add loading to tile component

- packages/misc/docs/stories/LinkButton.story.js
- packages/misc/src/components/LinkButton/index.tsx
- packages/misc/src/components/LinkButton/styled.js
- packages/misc/src/components/LinkButton/types.ts
> feat: add disabled prop to link button

- packages/forms/src/validators/isEmail.d.ts
- packages/forms/src/validators/isInteger.d.ts
- packages/forms/src/validators/isNumber.d.ts
- packages/forms/src/validators/isRequired.d.ts
- packages/forms/src/validators/isUrl.d.ts
- packages/forms/src/validators/max.d.ts
- packages/forms/src/validators/maxLength.d.ts
- packages/forms/src/validators/maxLength.js
- packages/forms/src/validators/min.d.ts
- packages/forms/src/validators/minLength.d.ts
- packages/forms/src/validators/minLength.js
#612 
fix: form validator args type
> fix: form validator args type

- packages/forms/src/components/UniversalFormModal/index.d.ts
- packages/forms/src/components/UniversalFormModal/index.js
#614 
fix: title type on universal form modal to support nodes
> fix: title type on universal form modal to support nodes

- packages/record/src/components/RecordField/index.d.ts
> fix: recordField does not allow to pass a component with props

- packages/firebase-hooks/src/firestore/useCollectionOnce.js
- packages/listview/docs/stories/FirestoreTable.story.js
- packages/listview/docs/stories/FirestoreTableWithCursors.story.js
- packages/listview/src/components/AuditLogs/index.tsx
- packages/listview/src/components/FirestoreTable/getQuery.js
- packages/listview/src/components/FirestoreTableWithCursors/helpers/getCollection.js
- packages/listview/src/components/FirestoreTableWithCursors/index.js
- packages/listview/src/helpers/collection.js
- packages/listview/src/helpers/collectionGroup.js
- packages/listview/src/helpers/firestoreIsomorphicCall.js
- packages/listview/src/helpers/getDocs.js
- packages/listview/src/helpers/hasOwnProperty.js
- packages/listview/src/helpers/index.js
- packages/listview/src/helpers/limit.js
- packages/listview/src/helpers/onSnapshot.js
- packages/listview/src/helpers/orderBy.js
- packages/listview/src/helpers/queryIsomorphicCall.js
- packages/listview/src/helpers/startAfter.js
- packages/listview/src/helpers/startAt.js
- packages/listview/src/helpers/where.js
- packages/listview/src/hooks/useFirestore.js
> fix: bunch of examples are crashing

- package.json
- packages/forms/docs/stories/UniversalFormModal.story.js
- packages/forms/src/components/UniversalFormModal/index.d.ts
- packages/forms/src/components/UniversalFormModal/index.js
- yarn.lock
> feat: implement borderRadius on UniversalFormModal component

- packages/forms/docs/stories/MultiPhoneNumberInput.story.js
- packages/forms/src/components/MultiPhoneNumberInput/index.tsx
- packages/forms/src/components/MultiPhoneNumberInput/utils.ts
- packages/forms/src/index.d.ts
- packages/forms/src/index.js
- Add missing key to fields list
- Remove unused function
- Export component from package index
> fix: improve MultiPhoneNumberInput
